#!/usr/bin/env bash
#
# install.sh — One-command installation script for MindFlow IBus engine
#
# Usage: ./install.sh
#
set -euo pipefail

# ---------------------------------------------------------------------------
# Paths
# ---------------------------------------------------------------------------
SCRIPT_DIR="$(cd "$(dirname "${BASH_SOURCE[0]}")" && pwd)"
INSTALL_DIR="$HOME/.local/share/mindflow"
IBUS_COMPONENT_DIR="$HOME/.local/share/ibus/component"
CONFIG_DIR="$HOME/.config/mindflow"
CONFIG_FILE="$CONFIG_DIR/config.json"

# ---------------------------------------------------------------------------
# Helper
# ---------------------------------------------------------------------------
info()  { printf '\033[1;34m[INFO]\033[0m  %s\n' "$*"; }
ok()    { printf '\033[1;32m[OK]\033[0m    %s\n' "$*"; }
error() { printf '\033[1;31m[ERR]\033[0m   %s\n' "$*" >&2; }

# ---------------------------------------------------------------------------
# 1. Create directories
# ---------------------------------------------------------------------------
info "Creating directories…"
mkdir -p "$INSTALL_DIR"
mkdir -p "$IBUS_COMPONENT_DIR"
mkdir -p "$CONFIG_DIR"
ok "Directories created"

# ---------------------------------------------------------------------------
# 2. Set up Python venv (if not already present)
# ---------------------------------------------------------------------------
if [ ! -d "$SCRIPT_DIR/venv" ]; then
    info "Creating Python virtual environment…"
    python3 -m venv "$SCRIPT_DIR/venv"
    ok "venv created"
else
    info "venv already exists — skipping creation"
fi

# ---------------------------------------------------------------------------
# 3. Install / upgrade Python dependencies
# ---------------------------------------------------------------------------
info "Installing Python dependencies…"
"$SCRIPT_DIR/venv/bin/pip" install --quiet --upgrade pip
"$SCRIPT_DIR/venv/bin/pip" install --quiet google-genai
ok "Dependencies installed"

# ---------------------------------------------------------------------------
# 4. Create launcher script
# ---------------------------------------------------------------------------
LAUNCHER="$INSTALL_DIR/mindflow-engine"
info "Writing launcher script to $LAUNCHER…"
cat > "$LAUNCHER" << 'LAUNCHER_EOF'
#!/usr/bin/env bash
# Auto-generated by MindFlow install.sh
SCRIPT_DIR="__PROJECT_DIR__"
cd "$SCRIPT_DIR"
source "$SCRIPT_DIR/venv/bin/activate"
exec python -m mindflow.engine "$@"
LAUNCHER_EOF

# Substitute actual project directory
sed -i "s|__PROJECT_DIR__|$SCRIPT_DIR|g" "$LAUNCHER"
chmod +x "$LAUNCHER"
ok "Launcher created and made executable"

# ---------------------------------------------------------------------------
# 5. Install IBus component XML (replace %LIBEXECDIR% with install dir)
# ---------------------------------------------------------------------------
info "Installing IBus component descriptor…"
sed "s|%LIBEXECDIR%|$INSTALL_DIR|g" \
    "$SCRIPT_DIR/data/mindflow.xml" \
    > "$IBUS_COMPONENT_DIR/mindflow.xml"
ok "IBus component XML installed"

# ---------------------------------------------------------------------------
# 6. Copy engine metadata
# ---------------------------------------------------------------------------
info "Copying engine metadata…"
cp "$SCRIPT_DIR/data/mindflow-engine.xml" "$INSTALL_DIR/mindflow-engine.xml"
ok "Engine metadata copied"

# ---------------------------------------------------------------------------
# 7. Create default config (only if not already present)
# ---------------------------------------------------------------------------
if [ ! -f "$CONFIG_FILE" ]; then
    info "Creating default config at $CONFIG_FILE…"
    cat > "$CONFIG_FILE" << 'CFG_EOF'
{
    "api_key": "",
    "model": "gemini-2.0-flash",
    "enabled": true,
    "debounce_ms": 300,
    "max_predictions": 3,
    "min_buffer_length": 3,
    "trigger_key": "space",
    "accept_key": "Tab"
}
CFG_EOF
    ok "Default config created"
else
    info "Config already exists — skipping"
fi

# ---------------------------------------------------------------------------
# 8. Restart IBus daemon
# ---------------------------------------------------------------------------
info "Restarting IBus daemon…"
ibus restart 2>/dev/null && ok "IBus restarted" || {
    warn_msg="Could not restart IBus (not running or not installed). "
    warn_msg+="You may need to log out and back in."
    printf '\033[1;33m[WARN]\033[0m  %s\n' "$warn_msg"
}

# ---------------------------------------------------------------------------
# 9. Done
# ---------------------------------------------------------------------------
echo ""
echo "=========================================="
echo "  MindFlow installed successfully! 🪄"
echo "=========================================="
echo ""
echo "Next steps:"
echo ""
echo "  1. Set your Gemini API key:"
echo "     Edit $CONFIG_FILE"
echo "     and set \"api_key\" to your key."
echo ""
echo "  2. Select MindFlow in IBus:"
echo "     Run 'ibus-setup', go to Input Method,"
echo "     and add 'MindFlow AI Autocomplete'."
echo ""
echo "  3. Switch to MindFlow:"
echo "     Press Super+Space or run:"
echo "       ibus engine mindflow"
echo ""
